# Decleare variables to be passed to into the templates.

replicaCount: 1

image:
  repository: tyguler/gowebapp
  # Overrides the image tag whose default is the chart appVersion.
  tag: "11543967261"
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: chart-example.local
      paths: 
      - path: /
        pathType: ImplementationSpecific
